=== torrust/torrents-importer-sample/data/database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rss">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="channel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="link" type="xs:string" />
                            <xs:element name="item">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string" />
                                        <xs:element name="category" type="xs:string" />
                                        <xs:element name="infohash" type="xs:string" />
                                        <xs:element name="guid" type="xs:string" />
                                        <xs:element name="link" type="xs:string" />
                                        <xs:element name="description" />
                                        <xs:element name="size" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:decimal" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== torrust/torrents-importer-sample/data/database.xml
<rss xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="database.xsd" xmlns:torrentsimportersmaple="https://github.com/torrust/torrents-importer-sample" version="2.0">
    <channel>
        <title>Mandelbrot Set Collection</title>
        <description>Torrents with Mandelbrot Set Images</description>
        <link>https://github.com/torrust/torrents-importer-sample</link>
        <item>
            <title>MandelBrot Set 01</title>
            <category>Fractal</category>
            <infohash>0c90fbf036e28370c1ec773401bc7620146b1d48</infohash>
            <guid>https://raw.githubusercontent.com/torrust/torrents-importer-sample/main/tests/fixtures/torrents/mandelbrot_set_01.torrent</guid>
            <link>https://raw.githubusercontent.com/torrust/torrents-importer-sample/main/tests/fixtures/torrents/mandelbrot_set_01.torrent</link>
            <description></description>
            <size>17130410419</size>
        </item>
    </channel>
</rss>
